### PR TITLE
Added more robust checking for array and object types

### PR DESCRIPTION
**Pull request by bringking**
instanceof Array and obj.constructor were failing to correctly check the
type of model objects when used in a cross frame scenario. This fixes
the issue.

### CODE REVIEW

**Comment by coderenaissance** [comment]
The problem makes sense (Array and Object in the context of one frame are not the same as Array and Object in the context of another) but I'm going to have to do some thinking if there is another way around this. I initially did testing around what the most performant way to check this was across browsers (including older IE) and the method I used was the best choice (though a cross frame scenario didn't occur to me). Adding the additional checks will slow things down for everyone to handle an edge case. I'll do some testing, if it's not to big of a hit I may add it. If it is perhaps I can provide a global crossFrameSafe boolean that conditionally allow additional checking.

It's an issue though to be sure... I'll give it some thought.

**Comment by bringking** [comment]
I think a global option would probably be an acceptable solution. It really is an edge case, that I really only ran into it due to the environment I am working in. Let me see if I can make the solution more appropriate and submit another request

**Comment by coderenaissance** [comment]
Thanks!

**Comment by bringking** [comment]
Here is a perf test to compare the trade-off in performance. Indeed, this seems to replicate your statement that using the cross-frame method is considerably slower. 

http://jsperf.com/cross-frame-type-checking-vs-non-cross-frame/3

**Comment by unsafecode** [comment]
I still have this issue with custom classes defined in TypeScript. The resulting JS output overrides the object constructor, so it does not match Object anymore, and nothing of my viewmodel gets updated this way...

**Pull request closed without merging**
